### ISSUE TITLE
How to change biblio-style with other csl style files?

### ISSUE THREAD

**Issue by winterwang** [pzhaonet/bookdownplus#21]
Hi, in regular rmarkdown environment, we can specify 
`csl: the-lancet.csl` 
in the header of the  .Rmd file. like this:
 
```
---
title: "Sample Document"
output: html_document
bibliography: bibliography.bib
csl: biomed-central.csl
---
```

How to tweak the similar things in your package?

**Comment by pzhaonet** [comment]
Hi. bookdownplus helps users to created bookdown templates. When a template is already created, you can change the .Rmd files as you like, and it has nothing to do with bookdownplus any more.

**Comment by winterwang** [comment]
I mean, when I am using the article template in your package, I wanted to change the style of bibliography into other journals like lancet or anything. 
I realised that there is a line:
`biblio-style: chicago`
in the `index.Rmd` file. 

Any suggestion about how can we specify other style of bibliography? 

Thanks

**Comment by pzhaonet** [comment]
https://github.com/rstudio/bookdown/issues/354

**Comment by winterwang** [comment]
Thanks for the link. But I still have the problem in changing the bibliography style.
I have tried that option and please have a look at my code in the file `index.Rmd` below: 

```
--- 
title: "My Manuscript"
author: "Student anonymous"
date: ""
Abstract: "blablabla" 
#acknowledgements: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
output:
  bookdown::pdf_book:
    template: tex/template_article.tex
    keep_tex: yes
    citation_package: natbib
#    latex_engine: xelatex
    toc_depth: 3
    toc_unnumbered: no
    toc_appendix: yes
    quote_footer: ["\\begin{flushright}", "\\end{flushright}"]
    pandoc_args: [ "--csl", "nature.csl" ]
bibliography: [bib/bib.bib]
#biblio-style: 
link-citations: yes
colorlinks: no  
# toc: no
lot: no
lof: no
site: bookdown::bookdown_site
---
```

And there are no error reports during the building, but the file output gave the exact same when we use `biblio-style: apalike`. 
![2017-11-02_192708](https://user-images.githubusercontent.com/1786055/32346066-fcd8fd34-c003-11e7-897e-4d22ec33fe05.png)
![2017-11-02_192649](https://user-images.githubusercontent.com/1786055/32346071-032d8c9a-c004-11e7-8bc9-24073edab406.png)

While the correct format should look like this: 
![2017-11-02_193115](https://user-images.githubusercontent.com/1786055/32346202-7a3707e4-c004-11e7-8318-f1120aa84966.png)
