### ISSUE TITLE
Authors from yaml in Elsevier Template

### ISSUE THREAD

**Issue by JVAQUEROM** [pzhaonet/bookdownplus#50]
Hi! First of course I would like to thank you for such a contribution like bookdownplus package. It is awesome to work within R to do all the process of publication.

There is a small detail in Elsevier template. You have to hardcode Authors' names, affiliations and email address. So It would be great to have it in the yaml header. I suggest that the yaml file work like this:

```
- Author:
  - Name: AAA
  - Afiliation: University XXX
  - Email: a@b.com
- Author:
  - Name: BBB
  - Afiliation: University YYY
  - Email: c@d.com
```

But I do not know how all the $for()$ syntax work and how to access "sub-" options inside of author. 

So I would be glad to work on a new template but I clearly need some help on this.
